# Gitleaks configuration
# https://github.com/gitleaks/gitleaks

[extend]
# Extend the default gitleaks config
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true
